Repository wikimedia/wikimedia-page-library, pull requests merged in 2019-07, with the labels that each got.

#211 Fix appearance of spans with specific background color
  demo/DemoArticles/ArticleRef.js
  demo/ThemeTransform.html
  src/transform/ThemeTransform.css
  src/transform/ThemeTransform.js
Labels: changes welcome

#196 Ensure collapsed tables are added to content_block divs, eliminating any parentNodes in between
  src/transform/CollapseTable.js
  test/transform/CollapseTable.test.js
Labels: changes welcome

#218 mobile-html: DOMRect object from InteractionHandler response cannot be decoded on iOS
  src/transform/ReferenceCollection.js
  test/transform/ReferenceCollection.test.js
Labels: bug, changes welcome

#222 Pass href with imageClicked action, don't pass natural size. Pass title and text for linkClicked actions
  src/pcs/c1/InteractionHandling.js
Labels: changes welcome

#223 Add getSelectionInfo
  docs/pcs/pcs.md
  src/pcs/c1/InteractionHandling.js
  src/transform/CollapseTable.js
  src/transform/SectionUtilities.ts
Labels: changes welcome

#227 Add ability to disable image loading, remove document parameter
  docs/pcs/pcs.md
  src/pcs/c1/Footer.js
  src/pcs/c1/L10N.js
  src/pcs/c1/Page.js
  src/pcs/c1/index.js
  test/pcs/c1/L10N.test.js
  test/pcs/c1/PageMods.test.js
Labels: changes welcome

#228 227followup
  package.json
  test/pcs/c1/L10N.test.js
  test/pcs/c1/Page.test.js
Labels: WIP, changes welcome

#231 Check for requestAnimationFrame before use
  src/pcs/c1/Page.js
  test/pcs/c1/Page.test.js
Labels: changes welcome
